# Generated by Django 6.0.6 on 2026-06-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="客户名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="客户编码"
                    ),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=100, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="联系电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="库位编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="库位名称")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("SHELF", "货架"),
                            ("BIN", "货位"),
                            ("AREA", "区域"),
                            ("FLOOR", "地面"),
                        ],
                        max_length=20,
                        verbose_name="库位类型",
                    ),
                ),
                ("capacity", models.IntegerField(default=0, verbose_name="容量")),
                (
                    "current_qty",
                    models.IntegerField(default=0, verbose_name="当前数量"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                ("description", models.TextField(blank=True, verbose_name="库位描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "库位",
                "verbose_name_plural": "库位",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="商品编码"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                (
                    "sku",
                    models.CharField(blank=True, max_length=100, verbose_name="SKU"),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=100, verbose_name="条码"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="商品分类"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="件", max_length=20, verbose_name="单位"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="重量(kg)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="体积(m³)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("min_stock", models.IntegerField(default=0, verbose_name="最低库存")),
                ("max_stock", models.IntegerField(default=0, verbose_name="最高库存")),
                ("description", models.TextField(blank=True, verbose_name="商品描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="供应商名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="供应商编码"
                    ),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=100, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="联系电话"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仓库名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="仓库编码"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="仓库地址")),
                ("description", models.TextField(blank=True, verbose_name="仓库描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("IN", "入库单"), ("OUT", "出库单")],
                        max_length=20,
                        verbose_name="订单类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="总金额",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "actual_quantity",
                    models.IntegerField(default=0, verbose_name="实际数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(blank=True, max_length=100, verbose_name="批次号"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.location",
                        verbose_name="库位",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单明细",
                "verbose_name_plural": "订单明细",
            },
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="调整单号"
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("INCREASE", "盘盈"),
                            ("DECREASE", "盘亏"),
                            ("TRANSFER", "调拨"),
                        ],
                        max_length=20,
                        verbose_name="调整类型",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="调整数量")),
                ("reason", models.TextField(blank=True, verbose_name="调整原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.location",
                        verbose_name="库位",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存调整",
                "verbose_name_plural": "库存调整",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.warehouse",
                verbose_name="所属仓库",
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="库存数量")),
                (
                    "batch_no",
                    models.CharField(blank=True, max_length=100, verbose_name="批次号"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.location",
                        verbose_name="库位",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
                "unique_together": {("product", "location", "batch_no")},
            },
        ),
    ]
